### ISSUE TITLE
website notes

### ISSUE THREAD

**Issue by AnitaMF** [LevyShaked/Assignments_rep#1]
Hi Shaked,

Your website is very nice and your cat looks very cute!

Regarding the content, I think it might be beneficial to include some information about your academic journey on your website. This could help visitors understand your research interests better.

:)
@szabgab

**Comment by LevyShaked** [comment]
Hi Anita, thank you!

**Comment by LevyShaked** [comment]
Academic journey was added, thanks

**Comment by LevyShaked** [comment]
Academic journey was added, thanks
